(function () {
    'use strict';

    G.images = {};

    G.images.keys = new Image();
    G.images.keys.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADYAAAAJCAMAAABOty+XAAAABlBMVEUAAAD//8waCf7LAAAARUlEQVR4AWNgJAswECvMgMFjYACRGAwoE51GaANCVCkgQLChNIKLaRuamRCAKQK3DdMpcNvgytFtQ7gAUxuGtykLSbIAAI8cAZxzfQ7cAAAAAElFTkSuQmCC';

    G.images.screen = new Image();
    G.images.screen.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAkCAMAAADvudnxAAAACVBMVEUAAAD//wD//8wSrcKEAAAAAXRSTlMAQObYZgAAACpJREFUeAFjYCIbUKaVgSwwqhUPGNU6qnVU66jWUa2jWkkCjIyMUBZFWgGy3gLL3paT/AAAAABJRU5ErkJggg==';

    G.images.font = new Image();
    G.images.font.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAAAGCAMAAADKQOOkAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAMtJREFUeAGNlAEOQjEIQ9v7X9qEEHxYTPZ/rFtTBhWcZLvA6i8P40YVlgB8M4Ui8/dMZWwisvTTy4JkbDeuSgQX1EQyMgr0787ffb1OAxv3ScRa7AyZlzVf9Ud0ZJlglA4mfzmq1p6vTmRntknDUlSchqlHLR2KylkoLD102H7rMJQ50tvsbZh4j3ToPSxcMg+07yN9G84oGN5DlYbx8ZgX4HgcJqywtQd4a7Mb0Xmdl5ZWbI7u+S9ir7DmCWRokiOt81rlaaPhjBR8AAPkAgjI8lDkAAAAAElFTkSuQmCC';

    G.images.playerStationary = new Image();
    G.images.playerStationary.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAaCAMAAACJtiw1AAAAHlBMVEUAAAAAAAAAAIAUd7UWg8eAgIDNAAD/AAD/3LH//wCS2XgoAAAAAXRSTlMAQObYZgAAAFlJREFUeAHNikEKwDAIBDcxWvv/D3eNsFBI752Do4MAbgJ5L0QiWUhk5OjA5fTRRSLzxUfwPryDF/suGHJ6dqASZP9K50CkUzBbawEcZn8KERcBakb0rcDyAGMqBMkoG/+IAAAAAElFTkSuQmCC';

    G.images.playerRunningLeft = new Image();
    G.images.playerRunningLeft.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKIAAAAaCAMAAAADtXcxAAAAHlBMVEUAAAAAAAAAAIAUd7UWg8eAgIDNAAD/AAD/3LH//wCS2XgoAAAAAXRSTlMAQObYZgAAAV1JREFUeNrV0kFygzAQRFEsgUTuf+EIoalW+IbOlllZr7pm2nGWPj9tFg3IgA95sSFDDnzIi6H9mOWOPPiQF0Of/SMBefAhL6S3/RUXAcmDD3kxlM65JQ8+5IX0uoqbhOTBh7w80naMBOTBh7w80p62XULy4ENeniklAcgDjeCF9LqKSQLy4ENeQK+rmPO6rv1TJQWsA5jQHJl8gXxCQYSbuZtSa70NAfpmNvxesZSCCDazkCC+yBodc4QqG7HPXKhTmeCU3Dsyws28roo9OleMt86xT0bpY846ypzGCDfjekCLjRFFqE4FLoX6aUi/XwK69Bwj3MzrqqiCF1LFvxHdh7RBxe8Rbub1gDYIjamXTaoc59otbCh6axsi2MzrAo2MM//yY2f/yXifbxI34zoAhin636zj42j4/4pmM68XnaBxERq28FXwBj1s5vUyA42LdC0oQPf5JnHzzfVfE54XNIPuc4gAAAAASUVORK5CYII=';

    G.images.playerRunningRight = new Image();
    G.images.playerRunningRight.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKIAAAAaCAMAAAADtXcxAAAAHlBMVEUAAAAAAAAAAIAUd7UWg8eAgIDNAAD/AAD/3LH//wCS2XgoAAAAAXRSTlMAQObYZgAAAVpJREFUeNrV0tFuwyAQRNEkYHD//4cbMJuxfLUaJW/moRKH0e7U7eNz/t5HN4AhG/Hit8sSsOQjXgg6+zgZePIRLxnInvszA08+4gVwp68oNGDIRKy4yOs4GXjyES+AG1bcZABPPuIlg7BtnAw8+YiXBGT79toz8OQjXjIQ6sMCLPmIF8L9Ko6TgScf8QK4U8U+f9ZaS1kCENWgJFVGJi7toCJiiJM5t/f+RcUQkZZFn5DWmioyhMnYroY1fg1hhAr75MvagCnRsEwRMcTJ3N77fK40VrwMvqx/NyoLqu7KIITJ6fYDRmRhj1BA9i80K5w/WgnR+5QkhMn5dlQMYOhc8br93EcRH9LkdHvkA/vHFepo2GJVbMe0mCBDCJOxXUeIu75+cPzJxqOc22kETv6hYkxq8tVxPfTfK3Iyt2NtS+4cNJ7QUUIDYDLbEKW4c1AAKmo9DIDJ2P4P8LQXNJHsNZYAAAAASUVORK5CYII=';
}());