(function () {
    'use strict';

    G.images = {};

    G.images.background = new Image();
    G.images.background.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAkCAMAAADvudnxAAAADFBMVEUAAAAAAIAAANyAgIDmc9uuAAAArUlEQVR4Ad3SsQ7CMBRD0fj2//8ZISJTyoubN7Bgpgid3iEZ6o75U0npUrxhS6J4H1V/pFkF+tW0UP0PylJqkDdY0361ovmWEjWhS5Gj9CgGta2p5XjuZdmm83Acx5BE3a7vVUiuSr7TreqbepvVilrPv86yfk3Xd2gKWNZveKOqRVW3Va2q3FW1ripXFarEqopqnKtt6mqfej+lnNeihFOmXKpsU76qbFKKamUf4t0Jg1Zint4AAAAASUVORK5CYII=';


    G.images.keys = new Image();
    G.images.keys.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADYAAAAJCAMAAABOty+XAAAABlBMVEUAAAD//8waCf7LAAAARUlEQVR4AWNgJAswECvMgMFjYACRGAwoE51GaANCVCkgQLChNIKLaRuamRCAKQK3DdMpcNvgytFtQ7gAUxuGtykLSbIAAI8cAZxzfQ7cAAAAAElFTkSuQmCC';

    G.images.screen = new Image();
    G.images.screen.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAkCAMAAADvudnxAAAACVBMVEUAAAD//wD//8wSrcKEAAAAAXRSTlMAQObYZgAAACpJREFUeAFjYCIbUKaVgSwwqhUPGNU6qnVU66jWUa2jWkkCjIyMUBZFWgGy3gLL3paT/AAAAABJRU5ErkJggg==';

    G.images.font = new Image();
    G.images.font.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAAAGCAMAAADKQOOkAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAMtJREFUeAGNlAEOQjEIQ9v7X9qEEHxYTPZ/rFtTBhWcZLvA6i8P40YVlgB8M4Ui8/dMZWwisvTTy4JkbDeuSgQX1EQyMgr0787ffb1OAxv3ScRa7AyZlzVf9Ud0ZJlglA4mfzmq1p6vTmRntknDUlSchqlHLR2KylkoLD102H7rMJQ50tvsbZh4j3ToPSxcMg+07yN9G84oGN5DlYbx8ZgX4HgcJqywtQd4a7Mb0Xmdl5ZWbI7u+S9ir7DmCWRokiOt81rlaaPhjBR8AAPkAgjI8lDkAAAAAElFTkSuQmCC';

    G.images.playerStationary = new Image();
    G.images.playerStationary.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAaCAMAAACJtiw1AAAAG1BMVEUAAAAAAAAUd7UWg8eAgIDNAAD/AAD/3LH//wD+TbStAAAAAXRSTlMAQObYZgAAAFlJREFUeNrNjkEKwDAIBDdGY///4rqKhEJy7xyy7iASAE+AzhxIB3HSQYaPEjGcNsp0kPXhIrSKllCSnfDWUqfIyLO523EWJOMmROacQDwifxJm+6dm3SnKvD86BWOst/iZAAAAAElFTkSuQmCC';

    G.images.playerRunningLeft = new Image();
    G.images.playerRunningLeft.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKIAAAAaCAMAAAADtXcxAAAAG1BMVEUAAAAAAAAUd7UWg8eAgIDNAAD/AAD/3LH//wD+TbStAAAAAXRSTlMAQObYZgAAAVpJREFUeAHV1VFuJCEMhGEG2vTe/8QbaJVM+CNqXttPy7cluzIaJWXOv58pGpIHH/LiQp48mJARQ/eYQvoWfMiLoc/9SQF58CEvpLd9igUAMmBCXgz1Zw7kwIe8kF5X8UohefAhL0e6xqSQPPiQlxPd/bpTSB58yMuZet+A5MGHvJBeVbGnkDz4kBfSyyrW2lp7/o8kaAlIaEamblAfCEa4mbsh2Z0hADc3NWLFiGCEm3ldoB+kqWNVqG+N0AeFBsUKU2pEMMLNvL5WnNG1Yr61nH0qSo+J+J2RIYLNuC6YsTlJCnV+ifSepynjfgimKMcIN/O6KqrgTmvFjKz3KbWi4t8RbsZ1wZg9pOnbpqysc5FSNJFvbWOEm3l9Aw1Mo89e/57RiOB9vkncjOsAGCbyu6nfrmr4dUWzmdcjT8A4gYYlYhe8D4TNvB4r0Lgor4nwRwvvA2Ezrv8HwHwZi9noM+IAAAAASUVORK5CYII=';

    G.images.playerRunningRight = new Image();
    G.images.playerRunningRight.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKIAAAAaCAMAAAADtXcxAAAAG1BMVEUAAAAAAAAUd7UWg8eAgIDNAAD/AAD/3LH//wD+TbStAAAAAXRSTlMAQObYZgAAAVdJREFUeNrV1dFug0AQQ9FmYaH//8XtAI5Rr0ZW88Y+dQ/WjEui9ut9vn+Pb4BAMZIlb5d1kClHshB89jodZMqRLB3YXvurg0w5kgXwpLdoDBAoRKKkyHaeDjLlSBbAAyuuNkCmHMnSgWyt00GmHMnSgG1ft72DTDmSpQOjXiwhU45kITyvYp0OMuVIFsCTKp4/LcsyhoggWkRNalRGl3nSECGEyZirvv+oKDF5mfpI5pyuyBAmY7sbLvo1jAoN9umXzYJD1HCUiBDCZGxXxePxQmNFvg4vq0p1VWndnUEIk9vtJ1Tkwk0hQfcVOircX9qQ6PklTQiT++2oKGDoXvHv9nsfR3LIk9vtygs3sUJlaDi1StsxTRNkCHEytvsYeffbF+sjq4d2bqcROPmDipo07VdH/Y39vCInczvWzubOQfUIHS00ACezDVHKOwcJwn88G4GTuf0HlWAZi4nu2O4AAAAASUVORK5CYII=';

    G.images.glitch = new Image();
    G.images.glitch.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAD1BMVEUAAACAgICmpqa0tLTAwMBW9+IOAAAAZklEQVR4AS3LAQoEIRTD0KbN/c+8+HcCUnxoUEBQ25JO/0gBAiaqW1IIqslM6PxedAnv0IMnWxJp1OX/JfYP4uh0tkGYstFXmIisA0q8WndrdHebH+AgF/0g8XpLBrMtgNDsCVK5fiSkAjR8RMHvAAAAAElFTkSuQmCC';

    G.images.glitchShot = new Image();
    G.images.glitchShot.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAD1BMVEUAAACAgICmpqa0tLTAwMBW9+IOAAAAZklEQVR4AT3NMULAABTCUAK5/5n1t1WGDG8hKCCobUmnL9JLwFV1qz1QE3dlI2B+t7f0H3aVRl3irusL4uh0tkGYstFbmIisA0p81jrVGl0riR/g4O/zA/WBqmQwu6QgNDtBKs9+AC4bAjws5NC8AAAAAElFTkSuQmCC'
}());